### ISSUE TITLE
[BUG] Your current repo won't install

### ISSUE THREAD

**Issue by 13thProgression** [wheatnetwork/wheat-blockchain#10]
**Describe the bug**
As in the title, your current repo won't install.
Error is: error: pathspec 'mozilla-ca' did not match any file(s) known to git

**To Reproduce**

1.) Clone to a fresh directory
2.) sh install.sh

**Expected behavior**
Repo gets installed and configured

**Screenshots**

**Desktop**

- OS: Linux- 
- OS Version/Flavor: Ubuntu 20.04
- CPU: AMD

**Additional context**
Initial commit installed without issue.  Was only after the forced push of difficulty changes that I noticed an issue.

**Comment by DCYeahThatsMe** [comment]
+1 same issue.

**Comment by Jsewill** [comment]
Same.

**Comment by Jsewill** [comment]
Those who wish to install this from this git repository while this submodule is still missing, please run `git submodule add https://github.com/Chia-Network/mozilla-ca` before running `sh install.sh`.

**Comment by Jsewill** [comment]
I've submitted a pull request (#11) to fix this issue.
