### ISSUE TITLE
[BUG] 1.2.201 on windows has the entire functionality binaries missing (start_farmer, start_full_node, all the cli stuff) and that is why the GUI does not open.

### ISSUE THREAD

**Issue by grayfallstown** [wheatnetwork/wheat-blockchain#15]
**Describe the bug**
Version 1.2.201 on Windows has the entire functionality binaries missing (start_farmer, start_full_node, all the cli stuff) and that is why the GUI does not open. daemon folder just does not exist.

**To Reproduce**

1. Install Version 1.2.201
2. Try to start it
3. See that nothing happens

**Expected behavior**
Version should come with all necessary binaries to run it / gui should start.

**Additional context**
Version 1.2.201 is only a bit over 100MB large, should be at least 140MB with all binaries. The release before is over 160MB large.

**Comment by wswzgit** [comment]
same

**Comment by wheatnetwork** [comment]
Sorry, the compilation directory was removed during packaging.
It is now available for redownload。
